# Generated by Django 5.1.7 on 2025-04-01 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=250)),
                ('required', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('data_type', models.CharField(choices=[('INT', 'int'), ('REAL', 'float'), ('TEXT', 'str'), ('DATE', 'date'), ('ENUM', 'enum'), ('BOOL', 'bool'), ('ARRAY', 'list'), ('OBJECT', 'dict')], default='str', max_length=8)),
                ('required', models.BooleanField()),
                ('specs', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ActionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('data_type', models.CharField(choices=[('INT', 'int'), ('REAL', 'float'), ('TEXT', 'str'), ('DATE', 'date'), ('ENUM', 'enum'), ('BOOL', 'bool'), ('ARRAY', 'list'), ('OBJECT', 'dict')], max_length=8)),
                ('specs', models.JSONField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.action')),
            ],
        ),
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('data_type', models.CharField(choices=[('INT', 'int'), ('REAL', 'float'), ('TEXT', 'str'), ('DATE', 'date'), ('ENUM', 'enum'), ('BOOL', 'bool'), ('ARRAY', 'list'), ('OBJECT', 'dict')], max_length=8)),
                ('specs', models.JSONField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('version', models.CharField(default='0.0.1', max_length=10)),
                ('actions', models.ManyToManyField(to='core.action')),
                ('events', models.ManyToManyField(to='core.event')),
                ('properties', models.ManyToManyField(to='core.property')),
            ],
        ),
    ]
