# Generated by Django 5.1.7 on 2025-04-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_action_created_dt_action_updated_dt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('product_pattern', models.CharField(max_length=100)),
                ('device_pattern', models.CharField(max_length=100)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='deviceshadow',
            old_name='creatd_dt',
            new_name='created_dt',
        ),
    ]
